### PR TITLE
Readme updates and adminlte update

### PR DESCRIPTION
**Pull request by stuartsoft**
### Is there test coverage for your changes?
  No, not needed. Mostly just `adminlte` and readme updates

### Major changes included in this PR:
- Adding github PR template
- Added readme for setting up development environment
- Updated adminlte
- Ignored a failing test and fixed a typo in an ansible file

### Special requirements for running/deploying this code:
- should probably just run ./bin/toxic-ui to make sure adminlte update worked without any issues

### Who should review this PR?
  @jertel @dotariel

### CODE REVIEW

**Comment by stuartsoft** [comment]
I'd recommend doing a `squash` when you merge this. It will condense all my commits down to a single commit.

**Comment by dotariel** [comment]
What does the update to AdminLTE provide? Are there any breaking changes?

**Comment by stuartsoft** [comment]
Looking through the release notes, looks like lots of bug fixed for `AdminLTE` and dependency updates.
I've booted up the local toxic server and didn't see anything immediately out of place. I don't have any projects setup in toxic yet, so I'm probably not the best person to test the UI.

**Comment by stuartsoft** [comment]
@dotariel  here's the full release notes copied from https://github.com/ColorlibHQ/AdminLTE/releases

AdminLTE 2.4.10
@almasaeed2010 almasaeed2010 released this on Mar 11 · 9 commits to master since this release

Release Notes
Fix #2071

AdminLTE 2.4.9
@almasaeed2010 almasaeed2010 released this on Feb 18 · 11 commits to master since this release

Upgrade dependencies to fix #2038

v2.4.8  …
AdminLTE v2.4.8

v2.4.7  …
AdminLTE v2.4.7

v2.4.6  …
AdminLTE v2.4.6

AdminLTE 2.4.5
@almasaeed2010 almasaeed2010 released this on Jul 14, 2018 · 24 commits to master since this release

Release Notes
A few fixes

AdminLTE 2.4.4
@almasaeed2010 almasaeed2010 released this on Jul 14, 2018 · 33 commits to master since this release

Release Notes
Update all plugins

AdminLTE 2.4.3
@almasaeed2010 almasaeed2010 released this on Feb 4, 2018 · 43 commits to master since this release

Release Notes
b3acb63 Update dependencies and fix issue #1741
281bb89 Update dependencies
51e96d8 Update ISSUE_TEMPLATE.md (#1751)
6d6d00a Fix Missing Chart.js File (#1738)
61dc63a Update bower.json
96b63a6 Create ISSUE_TEMPLATE.md (#1721)
278785a Add semicolons to support webpack
5339340 Don't hardcode slimscroll options. (#1605)
c3fb2e2 corrected error in the chart path in the charts pages (#1581)
f0421f5 Composer installer support (#1619)
a667b95 Fix box inside box collapsing error (#1681) (#1685)
b98b591 Change JS comment for better parsing (#1693)
d7f2e97 Fix issue #1692
d53319e Upgrade yarn.lock

AdminLTE 2.4.2
@almasaeed2010 almasaeed2010 released this on Oct 9, 2017 · 60 commits to master since this release

Release Notes
156f56c Fix background color

AdminLTE 2.4.1
@almasaeed2010 almasaeed2010 released this on Oct 8, 2017 · 61 commits to master since this release

Release Notes
A few bug fixes.

cc46542 Fix issue #1664 and update bower plugins
f14e4aa Fix issue #1665

**Comment by dotariel** [comment]
What specific bug or issue were you looking to address with the update?

**Pull request merged**
